#!/usr/bin/env bash
#ddev-generated
## Description: Run Codebase MCP server
## Usage: codebase-mcp
## Example: "ddev codebase-mcp"
## HostWorkingDir: false

/usr/bin/php /var/www/html/.ddev/codebase/scripts/CodebaseMCPServer.class.php
