#!/usr/bin/env bash
#ddev-generated
## Description: Run Codebase MCP server
## Usage: codebase-mcp
## Example: "ddev codebase-mcp"
## HostWorkingDir: false

php ./ddev/codebase/scripts/CodebaseMCPServer.class.php
